const aloneQuotes = [
    { quote: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne" },
    { quote: "Sometimes, you need to be alone. Not to be lonely, but to enjoy your free time.", author: "Unknown" },
    { quote: "In solitude, the mind gains strength and learns to lean upon itself.", author: "Laurence Sterne" },
    { quote: "I restore myself when I’m alone.", author: "Marilyn Monroe" },
    { quote: "The eternal quest of the human being is to shatter his loneliness.", author: "Norman Cousins" },
    { quote: "The only time we waste is the time we spend thinking we are alone.", author: "Mitch Albom" },
    { quote: "Loneliness is not a lack of company, loneliness is a lack of purpose.", author: "Guillermo Maldonado" },
    { quote: "Sometimes you have to stand alone to prove that you can still stand.", author: "Unknown" },
    { quote: "The best part about being alone is that you get to do whatever you want.", author: "Unknown" },
    { quote: "You have to be alone to be free.", author: "Unknown" },
    { quote: "Alone, we can do so little; together, we can do so much.", author: "Helen Keller" },
    { quote: "Loneliness and the feeling of being unwanted is the most terrible poverty.", author: "Mother Teresa" },
    { quote: "I think it’s good for a person to be alone sometimes, just to see how much they can take on their own.", author: "Unknown" },
    { quote: "Being alone has a power that very few can handle.", author: "Steven Aitchison" },
    { quote: "Solitude is fine, but you need someone to tell that solitude is fine.", author: "Honore de Balzac" },
    { quote: "Loneliness is a part of being human. It reminds us that we are not complete in ourselves.", author: "David Foster Wallace" },
    { quote: "Alone, I am a diamond in the rough. But with you, I am a jewel.", author: "Unknown" },
    { quote: "Sometimes, you just need to be alone to recharge and be the best version of yourself.", author: "Unknown" },
    { quote: "It is better to be alone than in bad company.", author: "George Washington" },
    { quote: "Solitude is the place of purification.", author: "Mary Sarton" },
    { quote: "In solitude, I find peace.", author: "Unknown" },
    { quote: "Loneliness is the poverty of self; solitude is the richness of self.", author: "May Sarton" },
    { quote: "You cannot be lonely if you like the person you’re alone with.", author: "Wayne Dyer" },
    { quote: "There is a difference between solitude and loneliness. Solitude is a chosen separation for refinement; loneliness is an unchosen isolation.", author: "Maya Angelou" },
    { quote: "I am never less alone than when alone.", author: "Cicero" },
    { quote: "Being alone is better than being with someone who makes you feel alone.", author: "Unknown" },
    { quote: "It is in solitude that we discover the most about ourselves.", author: "Unknown" },
    { quote: "Don’t be afraid of being alone. It’s a gift to yourself.", author: "Unknown" },
    { quote: "Alone, we are like a single star in the sky. Together, we form a galaxy.", author: "Unknown" },
    { quote: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne" },
    { quote: "There is nothing wrong with being alone. Sometimes you have to stand alone to be stronger.", author: "Unknown" },
    { quote: "The greatest pain that comes from love is loving someone you can never have.", author: "Unknown" },
    { quote: "It’s hard to forget someone who gave you so much to remember.", author: "Unknown" },
    { quote: "The worst feeling is not being lonely, it’s being forgotten by someone you would never forget.", author: "Unknown" },
    { quote: "Sometimes, the one who loves you is the one who hurts you the most.", author: "Unknown" },
    { quote: "Sadness is when everything is okay, but you still feel empty.", author: "Unknown" },
    { quote: "The heart was made to be broken.", author: "Oscar Wilde" },
    { quote: "Tears come from the heart and not from the brain.", author: "Leonardo da Vinci" },
    { quote: "It’s okay to not be okay, as long as you are not giving up.", author: "Karen Salmansohn" },
    { quote: "Sometimes the person you want the most is the person you’re best without.", author: "Unknown" },
    { quote: "The greatest loss is not death, but the loss of the will to live.", author: "Unknown" },
    { quote: "The sadness will last forever.", author: "Vincent van Gogh" },
    { quote: "People cry, not because they’re weak, but because they’ve been strong for too long.", author: "Johnny Depp" },
    { quote: "Don’t cry when the sun is gone, because the tears won’t let you see the stars.", author: "Violeta Parra" },
    { quote: "It’s painful to let go, but sometimes it’s the only thing to do.", author: "Unknown" },
    { quote: "Sometimes, you have to pretend that you’re happy just to keep going.", author: "Unknown" },
    { quote: "A broken heart is the price we pay for love.", author: "Unknown" },
    { quote: "The hardest thing is not talking to someone you used to talk to every day.", author: "Unknown" },
    { quote: "If you love someone, set them free. If they don’t come back, it was never meant to be.", author: "Unknown" },
    { quote: "Some people are meant to fall in love with each other, but not meant to be together.", author: "Unknown" },
    { quote: "The saddest thing is when you know you should let go, but you can’t.", author: "Unknown" },
    { quote: "Sometimes you have to let go of the one you love to find out if they really love you.", author: "Unknown" },
    { quote: "It’s easy to cry when you realize that everyone you love will reject you or die.", author: "Chuck Palahniuk" },
    { quote: "Don’t grieve. Anything you lose comes round in new form.", author: "Rumi" },
    { quote: "The only thing more painful than being hurt is hurting someone else.", author: "Unknown" },
    { quote: "When you’re feeling lost, you’ll find the best way to go forward is to first accept you are lost.", author: "Unknown" },
    { quote: "We never really get over a broken heart, we just learn to live with the pieces.", author: "Unknown" },
    { quote: "Some wounds never show on the body that are deeper and more hurtful than anything that bleeds.", author: "Unknown" },
    { quote: "You’ll never know the pain you caused me, but I’ll always remember it.", author: "Unknown" },
    { quote: "The only thing that hurts more than being disappointed by someone you love is knowing they don’t care.", author: "Unknown" },
    { quote: "The pain of the past never goes away; it simply transforms into a part of who we are.", author: "Unknown" },
    { quote: "It’s hard to forget someone who gave you so much to remember.", author: "Unknown" },
    { quote: "You can’t love someone back to life, even if you love them with everything you have.", author: "Unknown" }
];
