const animeQuotes = [
    { quote: "It's not the face that makes someone a monster; it's the choices they make with their lives.", author: "Naruto Uzumaki" },
    { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Kenshin Himura" },
    { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.", author: "Edward Elric" },
    { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku" },
    { quote: "You should enjoy the little detours. Sometimes they take you to the best places.", author: "Iruka Umino" },
    { quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way!", author: "Naruto Uzumaki" },
    { quote: "The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
    { quote: "People’s lives don’t end when they die, it ends when they lose faith.", author: "Naruto Uzumaki" },
    { quote: "I don't care if I die, but I want to be able to die knowing that I did everything I could.", author: "Kamina" },
    { quote: "If you don’t take risks, you can’t create a future!", author: "Monkey D. Luffy" },
    { quote: "You can’t sit around envying other people’s worlds. You have to go out and change your own.", author: "Naruto Uzumaki" },
    { quote: "A person grows up when he's able to overcome hardships.", author: "Jiraiya" },
    { quote: "If you don’t like the hand that fate’s dealt you with, fight for a new one.", author: "Naruto Uzumaki" },
    { quote: "I am not gonna lose to someone who doesn’t take risks.", author: "Natsu Dragneel" },
    { quote: "When you give up, that's when the game is over.", author: "Kuroko Tetsuya" },
    { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
    { quote: "To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.", author: "Mushishi" },
    { quote: "I’m not gonna give up, I’m not gonna run away!", author: "Monkey D. Luffy" },
    { quote: "The pain that you have to endure will make you stronger.", author: "Saitama" },
    { quote: "No matter what happens, never forget your friends. No matter how difficult it gets, never forget your friends.", author: "Naruto Uzumaki" },
    { quote: "You’re not alone. You’re never alone. As long as you’re alive, you have the potential to change your life!", author: "Hinata Hyuga" },
    { quote: "If you really want to change the world, you have to take it with your own hands.", author: "Izuku Midoriya" },
    { quote: "We’re all different, but there’s one thing we all share: the will to fight for something.", author: "Saitama" },
    { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Kenshin Himura" },
    { quote: "Even the most painful experiences can become the driving force to move forward.", author: "Natsu Dragneel" },
    { quote: "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!", author: "Shintaro Midorima" },
    { quote: "The only thing we're allowed to do is believe that we won’t regret the choice we made.", author: "Mikasa Ackerman" },
        { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.", author: "Edward Elric" },
        { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku" },
        { quote: "You should enjoy the little detours. Sometimes they take you to the best places.", author: "Iruka Umino" },
        { quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way!", author: "Naruto Uzumaki" },
        { quote: "The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
        { quote: "People’s lives don’t end when they die, it ends when they lose faith.", author: "Naruto Uzumaki" },
        { quote: "I don't care if I die, but I want to be able to die knowing that I did everything I could.", author: "Kamina" },
        { quote: "If you don’t take risks, you can’t create a future!", author: "Monkey D. Luffy" },
        { quote: "You can’t sit around envying other people’s worlds. You have to go out and change your own.", author: "Naruto Uzumaki" },
        { quote: "A person grows up when he's able to overcome hardships.", author: "Jiraiya" },
        { quote: "If you don’t like the hand that fate’s dealt you with, fight for a new one.", author: "Naruto Uzumaki" },
        { quote: "I am not gonna lose to someone who doesn’t take risks.", author: "Natsu Dragneel" },
        { quote: "When you give up, that's when the game is over.", author: "Kuroko Tetsuya" },
        { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
        { quote: "To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.", author: "Mushishi" },
        { quote: "I’m not gonna give up, I’m not gonna run away!", author: "Monkey D. Luffy" },
        { quote: "The pain that you have to endure will make you stronger.", author: "Saitama" },
        { quote: "No matter what happens, never forget your friends. No matter how difficult it gets, never forget your friends.", author: "Naruto Uzumaki" },
        { quote: "You’re not alone. You’re never alone. As long as you’re alive, you have the potential to change your life!", author: "Hinata Hyuga" },
        { quote: "If you really want to change the world, you have to take it with your own hands.", author: "Izuku Midoriya" },
        { quote: "We’re all different, but there’s one thing we all share: the will to fight for something.", author: "Saitama" },
        { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Kenshin Himura" },
        { quote: "Even the most painful experiences can become the driving force to move forward.", author: "Natsu Dragneel" },
        { quote: "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!", author: "Shintaro Midorima" },
        { quote: "The only thing we're allowed to do is believe that we won’t regret the choice we made.", author: "Mikasa Ackerman" },
        { quote: "When you give up, that’s when you know you have failed. Until then, keep moving forward.", author: "Yusuke Urameshi" },
        { quote: "The world is not perfect, but it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
        { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.", author: "Edward Elric" },
        { quote: "A person who can’t throw something important away, can never hope to change anything.", author: "Armin Arlert" },
        { quote: "Sometimes you have to get through the dark to see the light.", author: "Yuki Sohma" },
        { quote: "When you give up, that’s when you know you have failed. Until then, keep moving forward.", author: "Yusuke Urameshi" },
    { quote: "The world is not perfect, but it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
    { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.", author: "Edward Elric" },
    { quote: "A person who can’t throw something important away, can never hope to change anything.", author: "Armin Arlert" },
    { quote: "Sometimes you have to get through the dark to see the light.", author: "Yuki Sohma" },
    { quote: "Even the most painful experiences can become the driving force to move forward.", author: "Natsu Dragneel" },
    { quote: "It’s not the face that makes someone a monster; it’s the choices they make with their lives.", author: "Naruto Uzumaki" },
    { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
    { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku" },
    { quote: "You should enjoy the little detours. Sometimes they take you to the best places.", author: "Iruka Umino" },
    { quote: "The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
    { quote: "People’s lives don’t end when they die, it ends when they lose faith.", author: "Naruto Uzumaki" },
    { quote: "I don't care if I die, but I want to be able to die knowing that I did everything I could.", author: "Kamina" },
    { quote: "If you don’t take risks, you can’t create a future!", author: "Monkey D. Luffy" },
    { quote: "You can’t sit around envying other people’s worlds. You have to go out and change your own.", author: "Naruto Uzumaki" },
    { quote: "A person grows up when he's able to overcome hardships.", author: "Jiraiya" },
    { quote: "If you don’t like the hand that fate’s dealt you with, fight for a new one.", author: "Naruto Uzumaki" },
    { quote: "I am not gonna lose to someone who doesn’t take risks.", author: "Natsu Dragneel" },
    { quote: "When you give up, that's when the game is over.", author: "Kuroko Tetsuya" },
    { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
    { quote: "To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.", author: "Mushishi" },
    { quote: "I’m not gonna give up, I’m not gonna run away!", author: "Monkey D. Luffy" },
    { quote: "The pain that you have to endure will make you stronger.", author: "Saitama" },
    { quote: "No matter what happens, never forget your friends. No matter how difficult it gets, never forget your friends.", author: "Naruto Uzumaki" },
    { quote: "You’re not alone. You’re never alone. As long as you’re alive, you have the potential to change your life!", author: "Hinata Hyuga" },
    { quote: "If you really want to change the world, you have to take it with your own hands.", author: "Izuku Midoriya" },
    { quote: "We’re all different, but there’s one thing we all share: the will to fight for something.", author: "Saitama" },
    { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Kenshin Himura" },
    { quote: "Even the most painful experiences can become the driving force to move forward.", author: "Natsu Dragneel" },
    { quote: "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!", author: "Shintaro Midorima" },
    { quote: "The only thing we're allowed to do is believe that we won’t regret the choice we made.", author: "Mikasa Ackerman" },
    { quote: "When you give up, that’s when you know you have failed. Until then, keep moving forward.", author: "Yusuke Urameshi" },
    { quote: "The world is not perfect, but it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" },
    { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.", author: "Edward Elric" },
    { quote: "A person who can’t throw something important away, can never hope to change anything.", author: "Armin Arlert" },
    { quote: "Sometimes you have to get through the dark to see the light.", author: "Yuki Sohma" },
    { quote: "Even the most painful experiences can become the driving force to move forward.", author: "Natsu Dragneel" },
    { quote: "It’s not the face that makes someone a monster; it’s the choices they make with their lives.", author: "Naruto Uzumaki" },
    { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
    { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku" },
    { quote: "You should enjoy the little detours. Sometimes they take you to the best places.", author: "Iruka Umino" },
    { quote: "The world isn’t perfect. But it’s there for us, doing the best it can… that’s what makes it so damn beautiful.", author: "Roy Mustang" }    
];
