const familyQuotes = [
    { quote: "The family is the first essential cell of human society.", author: "Pope John XXIII" },
    { quote: "Family is a life jacket in the stormy sea of life.", author: "J.K. Rowling" },
    { quote: "What can you do to promote world peace? Go home and love your family.", author: "Mother Teresa" },
    { quote: "Family is not defined by our genes, it is built and maintained through love.", author: "Amalia G. M. Dillin" },
    { quote: "A family is the compass that guides us; it’s where life begins and love never ends.", author: "Unknown" },
    { quote: "In time of test, family is best.", author: "Burmese Proverb" },
    { quote: "To us, family means putting your arms around each other and being there.", author: "Barbara Bush" },
    { quote: "Family is the most important thing in the world.", author: "Princess Diana" },
    { quote: "Family is a gift that lasts forever.", author: "Unknown" },
    { quote: "The love of a family is life’s greatest blessing.", author: "Unknown" },
    { quote: "A family can develop only with a loving woman as its center.", author: "Karl Wilhelm Friedrich Schlegel" },
    { quote: "Family is the anchor that holds us through life’s storms.", author: "Unknown" },
    { quote: "The most important thing in the world is family and love.", author: "The Incredibles" },
    { quote: "The family is the most important unit in the world.", author: "Unknown" },
    { quote: "A man should never neglect his family for business.", author: "Walt Disney" },
    { quote: "A family is a patchwork of love.", author: "Unknown" },
    { quote: "Family is the greatest team you could ever have.", author: "Unknown" },
    { quote: "A family isn’t always blood. It’s the people in your life who want you in theirs; the ones who accept you for who you are.", author: "Unknown" },
    { quote: "The bond that links your true family is not one of blood, but of respect and joy in each other’s life.", author: "Richard Bach" },
    { quote: "Other things may change us, but we start and end with the family.", author: "Anthony Brandt" },
    { quote: "Home is where you are loved the most and act the worst.", author: "Marjorie Pay Hinckley" },
    { quote: "A family is a little world created by love.", author: "Unknown" },
    { quote: "Family gives you the roots to stand tall and strong.", author: "Unknown" },
    { quote: "A family is a place where you can be yourself without fear.", author: "Unknown" },
    { quote: "The family is the compass that guides us; it’s where life begins and love never ends.", author: "Unknown" },
    { quote: "There’s no place like home, except for the love of family.", author: "Unknown" },
    { quote: "Love your family, work super hard, live your passion.", author: "Gary Vaynerchuk" },
    { quote: "A family is what you make it. It’s made up of love, loyalty, and kindness.", author: "Unknown" },
    { quote: "It takes a village to raise a child.", author: "African Proverb" },
    { quote: "Family is the foundation that strengthens everything in life.", author: "Unknown" },
    { quote: "Family is where life begins and love never ends.", author: "Unknown" },
    { quote: "Family is not an important thing. It's everything.", author: "Michael J. Fox" },
    { quote: "The love of a family is life's greatest blessing.", author: "Unknown" },
    { quote: "Family means no one gets left behind or forgotten.", author: "David Ogden Stiers" },
    { quote: "A family is a place where minds come in contact with one another.", author: "Buddha" },
    { quote: "Other things may change us, but we start and end with the family.", author: "Anthony Brandt" },
    { quote: "Family is the compass that guides us; it’s where life begins and love never ends.", author: "Unknown" },
    { quote: "To us, family means putting your arms around each other and being there.", author: "Barbara Bush" },
    { quote: "Family is the most important thing in the world.", author: "Princess Diana" },
    { quote: "In family life, love is the oil that eases friction, the cement that binds us closer together, and the music that brings harmony.", author: "Friedrich Nietzsche" },
    { quote: "The family is one of nature's masterpieces.", author: "George Santayana" },
    { quote: "You don't choose your family. They are God's gift to you, as you are to them.", author: "Desmond Tutu" },
    { quote: "A family is a little world created by love.", author: "Unknown" },
    { quote: "Family is not an important thing. It’s everything.", author: "Michael J. Fox" },
    { quote: "Family: where life begins and love never ends.", author: "Unknown" },
    { quote: "In our family, there is no such thing as too much love.", author: "The Simpsons" },
    { quote: "The most important thing in the world is family and love.", author: "The Incredibles" },
    { quote: "The love of a family is life's greatest blessing.", author: "Unknown" },
    { quote: "A family is a team, and in our family, we all support each other.", author: "The Proud Family" },
    { quote: "Family is the foundation of a person's life.", author: "Unknown" },
    { quote: "Having a place to go is home. Having someone to love is family. Having both is a blessing.", author: "Unknown" },
    { quote: "Family is the first school for young children, and parents are powerful models.", author: "Jim Henson" },
    { quote: "The greatest gift of life is family and love.", author: "Unknown" },
    { quote: "Families are like branches on a tree. We grow in different directions yet our roots remain as one.", author: "Unknown" },
    { quote: "Family isn’t just important; it’s everything.", author: "Unknown" },
    { quote: "When everything goes to hell, the people who stand by you without flinching — they are your family.", author: "Jim Butcher" },
    { quote: "The family is the first essential cell of human society.", author: "Pope John XXIII" },
    { quote: "Family is a unique gift that needs to be appreciated and treasured.", author: "Jesse Tyler Ferguson" },
    { quote: "To be in your children’s memories tomorrow, you have to be in their lives today.", author: "Barbara Johnson" },
    { quote: "Family is the one constant in our lives.", author: "Unknown" },
    { quote: "Families are like fudge — mostly sweet with a few nuts.", author: "Leslie D. Weatherhead" },
    { quote: "Having a loving family is like having a soft place to land after every storm.", author: "Unknown" }
];
