const funnyQuotes = [
    { quote: "I’m on a whiskey diet. I’ve lost three days already.", author: "Tommy Cooper" },
    { quote: "I used to think I was indecisive, but now I'm not too sure.", author: "Unknown" },
    { quote: "My therapist says I have a preoccupation with vengeance. We'll see about that.", author: "Unknown" },
    { quote: "I told my wife she was drawing her eyebrows too high. She looked surprised.", author: "Unknown" },
    { quote: "I asked the gym instructor if he could teach me to do the splits. He replied, 'How flexible are you?' I said, 'I can't make it on Tuesdays.'", author: "Unknown" },
    { quote: "I don’t need a hair stylist, my pillow gives me a new hairstyle every morning.", author: "Unknown" },
    { quote: "The early bird might get the worm, but the second mouse gets the cheese.", author: "Steven Wright" },
    { quote: "Why don’t skeletons fight each other? They don’t have the guts.", author: "Unknown" },
    { quote: "I’m writing a book. I’ve got the page numbers done.", author: "Steven Wright" },
    { quote: "I’m not arguing, I’m just explaining why I’m right.", author: "Unknown" },
    { quote: "You can't have everything... where would you put it?", author: "Steven Wright" },
    { quote: "I don't suffer from insanity—I enjoy every minute of it.", author: "Unknown" },
    { quote: "I once spent a year in Philadelphia, I think it was on a Sunday.", author: "W. C. Fields" },
    { quote: "There are no stupid questions, just stupid people.", author: "Unknown" },
    { quote: "If you think nobody cares if you're alive, try missing a couple of payments.", author: "Earl Wilson" },
    { quote: "I'm writing a book. I've got the page numbers done.", author: "Steven Wright" },
    { quote: "When life gives you lemons, make lemonade. Then find someone whose life has given them vodka, and have a party.", author: "Ron White" },
    { quote: "A clear conscience is usually the sign of a bad memory.", author: "Steven Wright" },
    { quote: "I haven't spoken to my wife in years. I didn’t want to interrupt her.", author: "Rodney Dangerfield" },
    { quote: "I told my wife she was drawing her eyebrows too high. She looked surprised.", author: "Unknown" },
    { quote: "I'm on a whiskey diet. I’ve lost three days already.", author: "Tommy Cooper" },
    { quote: "I’m not afraid of commitment. I’m afraid of making the wrong commitment.", author: "Unknown" },
    { quote: "You know you're getting old when the candles cost more than the cake.", author: "Bob Hope" },
    { quote: "Money can’t buy happiness, but it can buy a yacht, and that’s pretty close.", author: "Unknown" },
    { quote: "I told my wife she should embrace her mistakes. She gave me a hug.", author: "Unknown" },
    { quote: "I’m on a rollercoaster that only goes up, my friend.", author: "Augustus Waters, The Fault in Our Stars" },
    { quote: "I always carry a pencil in case I need to draw a line.", author: "Unknown" },
    { quote: "There’s no 'we' in fries.", author: "Unknown" },
    { quote: "I’ve got a great diet. You should try it. I eat what I want, and then I sit down.", author: "Unknown" },
    { quote: "I’m trying to lose weight, but it’s not working. Maybe I should eat less and exercise more. Just kidding. I love food.", author: "Unknown" },
    { quote: "If you think nobody cares if you're alive, try missing a couple of payments.", author: "Earl Wilson" },
    { quote: "The best way to teach your kids about taxes is by eating 30% of their ice cream.", author: "Bill Murray" },
    { quote: "I'm on a diet. I’m not losing weight, I’m just losing my willpower.", author: "Unknown" },
    { quote: "I don't need a hair stylist. My pillow gives me a new hairstyle every morning.", author: "Unknown" },
    { quote: "I’m not arguing. I’m just trying to explain why I’m right.", author: "Unknown" },
    { quote: "It’s not that I’m lazy, it’s that I just don’t care.", author: "Unknown" },
    { quote: "I tried to lose weight, but it kept finding me.", author: "Unknown" },
    { quote: "I'm writing a book. I’ve got the page numbers done.", author: "Steven Wright" },
    { quote: "I used to be indecisive. Now I'm not sure.", author: "Unknown" },
    { quote: "I'm a multitasker. I can waste time, be unproductive, and procrastinate all at once.", author: "Unknown" },
    { quote: "I don’t have a problem with caffeine. I have a problem without caffeine.", author: "Unknown" },
    { quote: "I was going to take over the world, but I got distracted by something shiny.", author: "Unknown" },
    { quote: "I’m a huge fan of whiteboards. They’re re-markable.", author: "Unknown" },
    { quote: "I don't need Google. My wife knows everything.", author: "Unknown" },
    { quote: "I’m not great at advice. Can I interest you in a sarcastic comment?", author: "Chandler Bing, Friends" },
    { quote: "My life has a superb cast, but I can't figure out the plot.", author: "Ashleigh Brilliant" },
    { quote: "I’m not shy. I’m just good at figuring out who’s worth talking to.", author: "Unknown" },
    { quote: "Behind every great man, there is a woman rolling her eyes.", author: "Jim Carrey" },
    { quote: "I was going to give you a nasty look, but I see you already have one.", author: "Unknown" },
    { quote: "You know you’re texting too much when you say LOL instead of actually laughing out loud.", author: "Unknown" },
    { quote: "I don't suffer from insanity, I enjoy every minute of it.", author: "Unknown" },
    { quote: "If you don’t know where you’re going, any road will get you there.", author: "Lewis Carroll" },
    { quote: "I'd agree with you, but then we'd both be wrong.", author: "Unknown" },
    { quote: "I used to play piano by ear, but now I use my hands.", author: "Unknown" },
    { quote: "My password is the last 8 digits of pi.", author: "Unknown" },
    { quote: "If there’s a will, there’s a way. If there’s no will, there’s probably a lawsuit.", author: "Unknown" },
    { quote: "I just burned 1200 calories. I forgot the pizza in the oven.", author: "Unknown" },
    { quote: "I’m not arguing, I’m just explaining why I’m right.", author: "Unknown" },
    { quote: "I wonder if clouds ever look down on us and say, 'Hey, look! That one is shaped like an idiot.'", author: "Unknown" },
    { quote: "Life is short. Smile while you still have teeth.", author: "Unknown" },
    { quote: "If you can’t remember my name, just say 'milk' and I’ll turn around.", author: "Unknown" },
    { quote: "I don't need a mood ring. I have a face.", author: "Unknown" },
    { quote: "My wife and I are happy for 20 years. Then we met.", author: "Unknown" },
    { quote: "I’m a genius, but I choose to remain humble.", author: "Unknown" },
    { quote: "I don’t suffer from stress. I am the stress.", author: "Unknown" },
    { quote: "I’m on a diet. I’m losing weight, one meal at a time.", author: "Unknown" },
    { quote: "I’m on a seafood diet. I see food and I eat it.", author: "Unknown" },
    { quote: "I’m not arguing, I’m just explaining why I’m right.", author: "Unknown" },
    { quote: "My wife told me I should do lunges to stay in shape. That would be a big step forward.", author: "Unknown" },
    { quote: "I’d agree with you, but then we’d both be wrong.", author: "Unknown" },
    { quote: "I’m not lazy, I’m on energy-saving mode.", author: "Unknown" },
    { quote: "I put my phone in airplane mode, but it’s still on the ground.", author: "Unknown" },
    { quote: "I have a fear of speed bumps, but I am slowly getting over it.", author: "Unknown" },
    { quote: "I don't know what’s worse—getting older or not having enough time to do anything about it.", author: "Unknown" },
    { quote: "I love when my coffee kicks in and I realize what an adorable badass I’m going to be today.", author: "Unknown" },
    { quote: "I’m not procrastinating. I’m doing side quests.", author: "Unknown" },
    { quote: "I wish I were a glowworm, so I could eat my way out of a situation.", author: "Unknown" },
    { quote: "I don’t need a mood ring, I have a face.", author: "Unknown" },
    { quote: "I used to think I was indecisive, but now I’m not so sure.", author: "Unknown" },
    { quote: "I was going to take over the world, but I got distracted by something shiny.", author: "Unknown" },
    { quote: "My bed is a magical place where I suddenly remember everything I was supposed to do.", author: "Unknown" },
    { quote: "I don’t have an attitude problem. You have a perception problem.", author: "Unknown" },
    { quote: "If I won the award for laziness, I would send someone to pick it up for me.", author: "Unknown" },
    { quote: "I’m writing a book. I’ve got the page numbers done.", author: "Steven Wright" },
    { quote: "I’m not short. I’m vertically challenged.", author: "Unknown" },
    { quote: "My dog is smarter than your honor student.", author: "Unknown" },
    { quote: "I can't adult today. Please don't make me.", author: "Unknown" },
    { quote: "I'm reading a book on anti-gravity. It's impossible to put down.", author: "Unknown" },
    { quote: "I haven’t spoken to my wife in years. I didn’t want to interrupt her.", author: "Rodney Dangerfield" },
    { quote: "If you think nobody cares if you're alive, try missing a couple of payments.", author: "Earl Wilson" },
    { quote: "I don’t need an inspirational quote, I need coffee.", author: "Unknown" },
    { quote: "I’m on a whiskey diet. I’ve lost three days already.", author: "Tommy Cooper" },
    { quote: "I used to be indecisive, but now I’m not sure.", author: "Unknown" },
    { quote: "I’m not a morning person, I’m a coffee person.", author: "Unknown" },
    { quote: "I can't believe I got fired from the calendar factory. All I did was take a day off.", author: "Unknown" },
    { quote: "The only thing standing between me and total happiness is reality.", author: "Unknown" },
    { quote: "I don’t always make mistakes, but when I do, it’s usually on a Monday.", author: "Unknown" },
    { quote: "I'm trying to lose weight, but it’s not working. I’m finding it all over the place.", author: "Unknown" },
    { quote: "I came. I saw. I made it awkward.", author: "Unknown" },
    { quote: "If I had a dollar for every time I got distracted, I wish I had a puppy.", author: "Unknown" },
    { quote: "My goal this weekend is to move just enough so people don’t think I’m dead.", author: "Unknown" },
    { quote: "I don't need a mood ring. I have a face.", author: "Unknown" },
    { quote: "I never make the same mistake twice. I make it five or six times, just to be sure.", author: "Unknown" },
    { quote: "I like to hang out with people who make me forget to check my phone.", author: "Unknown" },
    { quote: "I think my guardian angel drinks.", author: "Unknown" },
    { quote: "My life is a sitcom, but no one’s laughing.", author: "Unknown" },
    { quote: "I was going to give you a nasty look, but I see you already have one.", author: "Unknown" },
    { quote: "I'm not arguing, I'm just explaining why I'm right.", author: "Unknown" },
    { quote: "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'", author: "Unknown" },
    { quote: "I’m not crazy, my reality is just different from yours.", author: "Unknown" },
    { quote: "I'm not shy, I'm just very good at figuring out who’s worth talking to.", author: "Unknown" },
    { quote: "I don’t suffer from insanity, I enjoy every minute of it.", author: "Unknown" },
    { quote: "I’m on a diet. I’m not losing weight, I’m just losing my willpower.", author: "Unknown" },
    { quote: "I’ll tell you a joke about a pencil, but it’s pointless.", author: "Unknown" },
    { quote: "I can't believe I forgot to go to the gym today. That’s 7 years in a row now.", author: "Unknown" },
    { quote: "I’m not lazy. I’m just on my energy-saving mode.", author: "Unknown" },
    { quote: "I don't know why I keep getting asked for ID at the grocery store. I’m obviously much too old to be a minor.", author: "Unknown" },
    { quote: "I'm not arguing, I’m just explaining why I’m right.", author: "Unknown" },
    { quote: "I’m a multitasker. I can waste time, be unproductive, and procrastinate all at once.", author: "Unknown" }
];
