const inspirationalQuotes = [
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
    { quote: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou" },
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
    { quote: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { quote: "Success is not measured by what you accomplish, but by the obstacles you overcome.", author: "Unknown" },
    { quote: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
    { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Dr. A.P.J. Abdul Kalam" },
    { quote: "Dream, dream, dream. Dreams transform into thoughts. And thoughts result in action.", author: "Dr. A.P.J. Abdul Kalam" },
    { quote: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda" },
    { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
    { quote: "You cannot believe in God until you believe in yourself.", author: "Swami Vivekananda" },
    { quote: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa" },
    { quote: "The only way to do great work is to love what you do.", author: "Ratan Tata" },
    { quote: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
    { quote: "If you want to fly, give up everything that weighs you down.", author: "Buddha" },
    { quote: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Hindu Proverb" },
    { quote: "When you are good to others, you are best to yourself.", author: "Mahatma Gandhi" },
    { quote: "Don't be afraid of being different, be afraid of being the same as everyone else.", author: "Swami Vivekananda" },
    { quote: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { quote: "Let us not pray to be sheltered from dangers but to be fearless when facing them.", author: "Rabindranath Tagore" },
    { quote: "The greatest thing is not to be afraid of your own voice.", author: "Kailash Satyarthi" },
    { quote: "What we think, we become.", author: "Buddha" },
    { quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
    { quote: "The more you sweat in practice, the less you bleed in battle.", author: "Vikram Sarabhai" },
    { quote: "There is no elevator to success — you have to take the stairs.", author: "Unknown" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Dr. A.P.J. Abdul Kalam" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Dr. A.P.J. Abdul Kalam" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "Man is the maker of his own destiny.", author: "Swami Vivekananda" },
    { quote: "It is not the years in your life that count, it’s the life in your years.", author: "Abraham Lincoln" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "Success is not in what you have, but who you are.", author: "Unknown" },
    { quote: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
    { quote: "Success comes from having a goal, knowing why you want it, and working hard every day to achieve it.", author: "Unknown" },
    { quote: "Let the life you live be your message.", author: "Mahatma Gandhi" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" }
];
