const lifeQuotes = [
    { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
    { quote: "In the end, we only regret the chances we didn’t take.", author: "Lewis Carroll" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
    { quote: "The purpose of life is to contribute in some way to making things better.", author: "Robert F. Kennedy" },
    { quote: "Life isn’t about waiting for the storm to pass. It’s about learning how to dance in the rain.", author: "Vivian Greene" },
    { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { quote: "Live life as if everything is rigged in your favor.", author: "Rumi" },
    { quote: "The purpose of life is to find your gift. The meaning of life is to give it away.", author: "Pablo Picasso" },
    { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { quote: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { quote: "Life is too important to be taken seriously.", author: "Oscar Wilde" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "In three words I can sum up everything I’ve learned about life: It goes on.", author: "Robert Frost" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce" },
    { quote: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { quote: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
    { quote: "It’s not the years in your life that count. It’s the life in your years.", author: "Abraham Lincoln" },
    { quote: "We do not remember days; we remember moments.", author: "Cesare Pavese" },
    { quote: "Life is too short to wait.", author: "Unknown" },
    { quote: "Life is a one-time offer, use it well.", author: "Unknown" },
    { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { quote: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.", author: "Unknown" },
    { quote: "Our lives are what our thoughts make it.", author: "Marcus Aurelius" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "In the end, it's not the years in your life that count, it's the life in your years.", author: "Abraham Lincoln" },
    { quote: "The unexamined life is not worth living.", author: "Socrates" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { quote: "Life is a question and how we live it is our answer.", author: "Gary Keller" },
    { quote: "Live your life in such a way that when your feet hit the floor in the morning, Satan shudders and says, 'Oh no, they’re awake!'", author: "Unknown" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "We live in capitalism. Its power seems inescapable. So did the divine right of kings.", author: "Sylvia Plath" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "It’s never too late to be what you might have been.", author: "George Eliot" },
    { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
    { quote: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
    { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
    { quote: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { quote: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda" },
    { quote: "The greatest religion is to be true to your own nature. Have faith in yourselves.", author: "Swami Vivekananda" },
    { quote: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Mahatma Gandhi" },
    { quote: "You cannot believe in God until you believe in yourself.", author: "Swami Vivekananda" },
    { quote: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill (but popular in India)" },
    { quote: "The mind is everything. What you think, you become.", author: "Buddha" },
    { quote: "When you are good to others, you are best to yourself.", author: "Mahatma Gandhi" },
    { quote: "The future depends on what we do in the present.", author: "Mahatma Gandhi" },
    { quote: "Let us not pray to be sheltered from dangers but to be fearless when facing them.", author: "Rabindranath Tagore" },
    { quote: "Nothing is more precious than independence and liberty.", author: "Subhas Chandra Bose" },
    { quote: "We are all born with a divine spark within us. It is our job to awaken it and make it shine.", author: "Swami Vivekananda" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
    { quote: "Take risks in your life. If you win, you can lead; if you lose, you can guide.", author: "Swami Vivekananda" },
    { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { quote: "Success is not in what you have, but who you are.", author: "Swami Vivekananda" }
];
