const moviesQuotes = [
    { quote: "May the Force be with you.", author: "Star Wars" },
    { quote: "Here's looking at you, kid.", author: "Casablanca" },
    { quote: "You can't handle the truth!", author: "A Few Good Men" },
    { quote: "I'll be back.", author: "The Terminator" },
    { quote: "Life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump" },
    { quote: "Why so serious?", author: "The Dark Knight" },
    { quote: "To infinity and beyond!", author: "Toy Story" },
    { quote: "I'm gonna make him an offer he can't refuse.", author: "The Godfather" },
    { quote: "Just keep swimming.", author: "Finding Nemo" },
    { quote: "There’s no place like home.", author: "The Wizard of Oz" },
    { quote: "I see dead people.", author: "The Sixth Sense" },
    { quote: "You talking to me?", author: "Taxi Driver" },
    { quote: "Nobody puts Baby in a corner.", author: "Dirty Dancing" },
    { quote: "It's not who I am underneath, but what I do that defines me.", author: "Batman Begins" },
    { quote: "The name’s Bond. James Bond.", author: "James Bond Series" },
    { quote: "I feel the need... the need for speed.", author: "Top Gun" },
    { quote: "Keep the change, ya filthy animal!", author: "Home Alone" },
    { quote: "I coulda been a contender. I could’ve been somebody.", author: "On the Waterfront" },
    { quote: "You had me at 'hello'.", author: "Jerry Maguire" },
    { quote: "Hoo-ah!", author: "Scent of a Woman" },
    { quote: "Carpe Diem. Seize the day, boys. Make your lives extraordinary.", author: "Dead Poets Society" },
    { quote: "Why are you trying so hard to fit in when you were born to stand out?", author: "What a Girl Wants" },
    { quote: "After all, tomorrow is another day.", author: "Gone with the Wind" },
    { quote: "I’m the king of the world!", author: "Titanic" },
    { quote: "You had me at hello.", author: "Jerry Maguire" },
    { quote: "You’re gonna need a bigger boat.", author: "Jaws" },
    { quote: "What we have here is a failure to communicate.", author: "Cool Hand Luke" },
    { quote: "There’s no place like home.", author: "The Wizard of Oz" },
    { quote: "I am Groot.", author: "Guardians of the Galaxy" },
    { quote: "This is the start of a beautiful friendship.", author: "Casablanca" },
    { quote: "A martini. Shaken, not stirred.", author: "James Bond Series" }
];
