const webseriesQuotes = [
    { quote: "I am the one who knocks!", author: "Breaking Bad" },
    { quote: "Winter is coming.", author: "Game of Thrones" },
    { quote: "Bhaukaal aayega, Bas! Be ready.", author: "Mukkabaaz, Mirzapur" },
    { quote: "I have a feeling I’m gonna enjoy this.", author: "Kartik Aaryan, *Aashram*" },
    { quote: "Zindagi mein jo kuch bhi hota hai, ek wajah hoti hai.", author: "Mirzapur, Guddu Pandit" },
    { quote: "Aapka time aayega, bas uss waqt apna dimaag lagana.", author: "Anurag Kashyap, *Sacred Games*" },
    { quote: "Agar koi cheez dil se chahiye, toh puri duniya usko tum tak pohcha deti hai.", author: "Sacred Games" },
    { quote: "Hamaare paas maan hai, power hai, dhanda hai. Tumhare paas kya hai?", author: "Mirzapur, Kaleen Bhaiya" },
    { quote: "Jab tak toote nahi, tab tak kuch haath nahi aata.", author: "Gully Boy, *Inside Edge*" },
    { quote: "Duniya ki sabse khatarnak cheez hai insaan ka khud se badla lena.", author: "Aarya, *Aarya*" },
    { quote: "Mujhe jo karna hai, main karunga, samajhdar hoon, main sab samajh raha hoon.", author: "Stranger Things" },
    { quote: "Ghar ki lakshmi ghar ke andar rehti hai.", author: "Made in Heaven" },
    { quote: "We all have to die. But it doesn’t matter if it’s today, tomorrow or the next day.", author: "The Family Man" },
    { quote: "Mujhe kuch nahi pata. Sirf apna kaam karne aaya hoon.", author: "Mirzapur" },
    { quote: "Main kuchh nahi maanta. Main apne kaam pe vishwas karta hoon.", author: "Money Heist (La Casa de Papel)" },
    { quote: "Zindagi mein jab sab kuch khatam ho jaye, toh ghar jaake so jao.", author: "Delhi Crime" },
    { quote: "Kuch cheezon ko jaane dena zaroori hai, taaki naye rishtey ban sakein.", author: "Made in Heaven" },
    { quote: "Thodi dosti, thoda dimaag aur sab kuchh badal sakta hai.", author: "Sacred Games" },
    { quote: "Main aapko maarne nahi aaya hoon, sirf aapka dimaag kholne aaya hoon.", author: "The Family Man" },
    { quote: "Agar tumhe apni kahani ko sach banana hai toh, toh uss kahani ko apne nazariye se dekhna hoga.", author: "The Crown" },
    { quote: "Kuch paane ke liye kuch kho dena padta hai.", author: "Sacred Games" },
    { quote: "Ye jo sapne hum dekhte hain, unki koi taqat nahi hoti.", author: "Paatal Lok" },
    { quote: "Har koi apne raste pe chalke apni manzil tak nahi pahuchta.", author: "The Family Man" },
    { quote: "Apni manzil se zyada apna raste ka intezaar mat karo.", author: "Inside Edge" },
    { quote: "Khud ko samajhne ki koshish karo, sab kuch badal jayega.", author: "Inside Edge" },
    { quote: "Aaj se yeh zindagi meri hai, aur jo kuch main chahoonga, main karunga.", author: "Gully Boy" },
    { quote: "Waqt ke sath chalna hoga. Kismat ke saath nahi.", author: "Mirzapur" },
    { quote: "Mujhe apni khoj nikalne ka waqt chahiye.", author: "Sacred Games" },
    { quote: "Har cheez ke peeche ek wajah hoti hai, agar tum samajh paaye, toh aage badhna asaan hoga.", author: "Scam 1992" },
    { quote: "Kuch bhi ho, baat dil se karo, aur manzil tak pahuchne ki koshish karo.", author: "Scam 1992" },
    { quote: "Hamesha apne dimaag se kaam lo, dil ki sunna thoda risky hota hai.", author: "Sacred Games" },
    { quote: "Kabhi kabhi apni galtiyan sabse zyada zaroori hoti hai, kyunki unse kuch seekhne ko milta hai.", author: "Made in Heaven" },
    { quote: "Agar tum apne sapno ko sach karna chahte ho, toh apne rishtey thoda kamzor kar lo.", author: "Sacred Games" },
    { quote: "Kabhi kabhi sach mein apni zindagi ka ek hisaab lena padta hai.", author: "The Family Man" },
        { quote: "Dil ki suno, aur dimaag se kaam lo.", author: "The Family Man" },
        { quote: "Aaj ki duniya mein, apne liye jeena sabse mushkil kaam hai.", author: "Scam 1992" },
        { quote: "Jo tumhare liye hai, wo tumhare paas zaroor aayega.", author: "Sacred Games" },
        { quote: "Agar tum khud par vishwas nahi karoge, toh koi tum par vishwas nahi karega.", author: "Money Heist" },
        { quote: "Zindagi mein apne faisle khud lo, koi aur nahi.", author: "Mirzapur" },
        { quote: "Agar koi cheez tumhein sach mein chahiye, toh uska peechha karo.", author: "Inside Edge" },
        { quote: "Life is all about finding the balance between being yourself and being a version of someone that others can relate to.", author: "GLOW" },
        { quote: "Hum insaan hain, har galti karte hain. Par galti pe seekhne ki taqat hona zaroori hai.", author: "Made in Heaven" },
        { quote: "Suno, duniya ka sabse bada sauda hamesha apne dimaag se hota hai.", author: "Scam 1992" },
        { quote: "Pyar karna sabse asaan hai, lekin pyar ko samajhna sabse mushkil.", author: "Little Things" },
        { quote: "Kyunki apne raste pe chalna zaroori hai, doosron ke raste pe chalna sirf thodi der tak chal sakta hai.", author: "Delhi Crime" },
        { quote: "Kuch cheezon ko samajhna zindagi ka sabse bada kaam hota hai.", author: "Sacred Games" },
        { quote: "Agar tum apni zindagi ka ek kadam samajhdari se uthao, toh har cheez badal sakti hai.", author: "The Family Man" },
        { quote: "Agar tum apne rakhwale ko samajh rahe ho, toh tumhe baaki sab kuchh samajhna asaan ho jata hai.", author: "Mirzapur" },
        { quote: "Mujhe khud pe pura vishwas hai, isliye duniya ki koi taqat mujhe rok nahi sakti.", author: "Money Heist" },
        { quote: "Agar tum khud se pyar nahi karoge, toh aur koi tumhe kabhi pyaar nahi karega.", author: "Made in Heaven" },
        { quote: "Jo kuch tumne chhupa ke rakha tha, wo sab samne aa jayega.", author: "Scam 1992" },
        { quote: "Life mein sab kuchh time pe hota hai, bas apni understanding badhao.", author: "The Crown" },
        { quote: "Zindagi ko apni tarah jeena zaroori hai, doosron ke hisaab se nahi.", author: "Inside Edge" },
        { quote: "Main kisi ke liye nahi, apne liye jeeta hoon.", author: "Sacred Games" },
        { quote: "Pehle apne aap ko samajhna padta hai, tabhi kisi aur ko samajh paoge.", author: "The Family Man" },
        { quote: "Hamesha apne man ka rasta apnana, warna kuch bhi nahi milega.", author: "Scam 1992" },
        { quote: "Aapka sabse bada doston ka rishta apne apne saath hona chahiye.", author: "Little Things" },
        { quote: "Agar tum har cheez ka pehle sochoge, toh kabhi kuch nahi kar paoge.", author: "Money Heist" },
        { quote: "Apne sapne sach karne ka waqt sabko milta hai, bas apne hausle se kaam lo.", author: "Made in Heaven" },
        { quote: "Zindagi mein doston ka role sabse important hai, kabhi kabhi aapko bas apne dost ke saath chalna hota hai.", author: "Mirzapur" },
        { quote: "Agar tum apne sapno ko jeevant karne ki koshish karoge, toh duniya tumhare peeche chalegi.", author: "The Family Man" },
        { quote: "Agar tum apni safalta chahte ho, toh tumhe apne vichar thik rakhne honge.", author: "Inside Edge" },
        { quote: "Kyunki kabhi kabhi apni feelings ko samajhna sabse bada challenge hota hai.", author: "Delhi Crime" }
        
];